### ISSUE TITLE
Porting to ROS 2 ?? 

### ISSUE THREAD

**Issue by artivis** [ros-teleop/twist_mux#14]
Is there already an effort in porting this package to ROS 2 ?? 
If not, I am willing to do it as a ROS 2 exercise. 
[This question on Discourse](https://discourse.ros.org/t/twist-mux-teleop-tools-porting-to-ros2/9448).

**Comment by bmagyar** [comment]
Not that I know of. I have just branched dashing-devel off of melodic-devel, please feel free to submit a PR

**Comment by efernandez** [comment]
No. I'll be happy to help, but I'm very busy atm.

**Comment by DLu** [comment]
Ok to close?
