### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [ros-teleop/twist_mux#19]
Would you mind releasing this package also for the newest distribution ROS Noetic? :)

(And also it's dependency `twist_mux_msgs`)

**Comment by doisyg** [comment]
@Timple, it seems you we have the same needs

**Comment by xelfe** [comment]
need it too ! please !

**Comment by bmagyar** [comment]
`twist_mux_msgs` is released to Noetic: https://github.com/ros/rosdistro/pull/25228

**Comment by xelfe** [comment]
@bmagyar are you planning  to do the twist_mux base package ?

**Comment by bmagyar** [comment]
There you go lads: https://github.com/ros/rosdistro/pull/25265

**Comment by bmagyar** [comment]
Guys, I will be closing this issue now. Please get back to us with PR-s should something in the release be broken.
