### ISSUE TITLE
BSD License

### ISSUE THREAD

**Issue by veimox** [ros-teleop/twist_mux#23]
Hi!

I really like this simple and effective package but after doing a license analysis of many packages I find a bit weird that this is released as `CC BY-NC-SA 4.0` whilst the rest of the packages of this Github organization is `BSD`. I was wondering what was the rationale behind this move and if it was possible to homogenize all licenses :smile:

**Comment by andresgalaviz** [comment]
+1

**Comment by peci1** [comment]
This is actually quite a problem, I'd say. As the license is non-commercial, how come e.g. Clearpath uses twist_mux in the official drivers for their commercially offered platforms such as Husky?

I think CC BY-SA would better fit the general ROS ideology. Or, BSD, of course :) But to change the license, all contributors would probably need to agree, am I right?

**Comment by bmagyar** [comment]
For ROS2 we've relicensed it all to Apache 2.

**Comment by peci1** [comment]
@bmagyar That's definitely good. But how was this relicensing done? Have you contacted all previous authors and get their permission to change the license (as the original license is Share-Alike which requires derived works to keep the license)? Or did you just contact PAL robotics as the copyright owner described in the header files?

I'm asking to figure out whether it'd be possible to re-license this work under Apache 2.0 also for ROS 1.

**Comment by bmagyar** [comment]
I made a pull request and contacted PAL Robotics. Asked that not only they agree but a PAL employee signs off on the PR so there's also evidence of the approval out in public, on GitHub.

**Comment by peci1** [comment]
Thanks for the quick reply! But I can't find the PR. I found the commit: https://github.com/ros-teleop/twist_mux/commit/c6d4926b7bcf80a66d5118445bce33c84d431180 . But it is not associated with a PR.

Generally, the approach sounds reasonable. I might try something similar for ROS 1. Or do you have an indication that they'd like it to stay as it is on ROS 1?

**Comment by bmagyar** [comment]
I cannot confirm nor deny. Just talk to them ;)
