### ISSUE TITLE
Release for Galactic

### ISSUE THREAD

**Issue by tonybaltovski** [ros-teleop/twist_mux#30]
Could you please do a release for Galactic?

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/31308

**Comment by bmagyar** [comment]
also pushed to rolling: https://github.com/ros/rosdistro/pull/31309

**Comment by bmagyar** [comment]
let me know if you are happy with these

**Comment by tonybaltovski** [comment]
Awesome, thank you!

**Comment by lourencorcc** [comment]
Do these work on Humble?

**Comment by bmagyar** [comment]
It should be... I think the first release was Foxy
